### ISSUE TITLE
QueryCache fetching related object is not invalidated when updating referenced object

### ISSUE THREAD

**Issue by OndrejPacay** [ebean-orm/ebean-ignite#3]
Hi Rob, 

let's say I have 2 models:
-  **Customer**  - with fields id,  name and **address** of type **Address**
-  **Address** - with fields id, city

I create a query (query1) :
`List<Customer> list = Customer.find.query().setUseQueryCache(true).fetch("address").
                                where().eq("name", "John").findList();`

The result is retrieved from the DB, stored in the query cache. In the result I get some value of the city.
The next time the result will be retrieved from the query cache:
`[debug] o.a.e.c.QUERY -    GET Customer(HashQuery@94f31ac3) - hit`

Then I update the Address object with city="London".  I see:
`[debug] o.a.e.c.QUERY -    CLEAR Address`
`[debug] o.a.e.c.BEAN -    UPDATE Address(1)  changes:{city=London}`

If I execute the query1 again I will get old city value from the cache.

Is it a bug or I am missing something?

Thank you for your great work. 
Ondrej

Versions used:
com.typesafe.play:play_2.11:2.5.6
org.avaje.ebean:ebean:8.2.3
org.avaje.ebean:ebean-ignite:1.3.2

**Comment by rbygrave** [comment]
So currently with the "Query cache" ... queries for Customer are invalidated by changes to customer only.  So the change to the related address does not invalidate the cache entry (and hence you get a hit on the existing cache entry and see the old address).

Ideally we can improve on this.

There is a general design that we don't want to "dynamically" determine what to invalidate against (e.g. dynamically determine that we want to invalidate cached customer queries when address changes) as then Ebean doesn't know what invalidation messages it needs to send to the rest of the cluster (given that different Ebean instances can have different states, some instances never have the customer + address combination so those instances don't send address changes to the rest of the cluster).

If we look at @View  that has dependentTables as a deployment property. That allows us to define the set of tables to watch for L2 cache invalidation.

I wonder if there should be a similar option on @Cache for controlling query cache invalidation.
e.g.

```java
@Entity
@Cache(enableQueryCaching=true, dependantTables={"address"})
public class Customer {
  ...
}
```
So then Ebean would know explicitly that changes to the address table are important for L2 cache invalidation and that these changes should effectively invalidate the customer query cache. 

Hmmm, I'll think on that some more but the above seems a reasonable improvement. (That is, with Ebean we have moved away from "dynamically determining what invalidation is important for L2" and so following the explicit dependantTables seems like the right approach).

**Comment by OndrejPacay** [comment]
Hi, 

I was thinking about the `@Cache` annotation enhancement that you proposed. 
I see a very narrow use case where it would be helpful, since there usually exist multiple queries using the model, each dependent on different sub-objects.  In my opinion the best approach is just to note that behaviour in the documentation about L2 cache use in Ebean. If somebody needs complex query cache invalidation, he probably should use L3 cache.

Regards, Ondrej

**Comment by rbygrave** [comment]
Closing now.
